BirdRecogniser02/Controllers/RecogniseDemoController.cs
using BirdRecogniser02.ImageHelpers;
using BirdRecogniser02.ML.DataModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.ML;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Microsoft.AspNetCore.Authorization;

namespace BirdRecogniser02.Controllers
{
    [AllowAnonymous]
    public class RecogniseDemoController : Controller
    {

        public IActionResult Index()
        {
            return View();
        }
    }
}

BirdRecogniser02/Controllers/SubmissionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BirdRecogniser02.Data;
using BirdRecogniser02.Models;
using Microsoft.Extensions.Hosting;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using BirdRecogniser02.Authorization;

namespace BirdRecogniser02.Controllers
{


    public class SubmissionsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _hostEnvironment;
        private readonly IAuthorizationService _authorizationService;
        private readonly UserManager<IdentityUser> _userManager;
        public SubmissionsController(ApplicationDbContext context, IWebHostEnvironment hostEnvironment, IAuthorizationService authorizationService, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _hostEnvironment = hostEnvironment;
            _authorizationService = authorizationService;
            _userManager = userManager;
        }

        // GET: Submissions
        public async Task<IActionResult> Index()
        {

            //-----------------------------------------------------
            var submission = from s in _context.Submission
                              select s;

            var isAuthorized = User.IsInRole(Constants.SubmissionManagersRole) ||
                               User.IsInRole(Constants.SubmissionAdministratorsRole);

            var currentUserId = _userManager.GetUserId(User);

            // Only approved contacts are shown UNLESS you're authorized to see them
            // or you are the owner.
            if (!isAuthorized)
            {
                submission = submission.Where(s => s.Status == SubmissionStatus.Approved ||
                                             s.OwnerID == currentUserId);
            }

            return submission != null ?
                   View(await submission.ToListAsync()) :
                   Problem("Entity set 'ApplicationDbContext.Submission'  is null.");
        }

        // GET: Submissions/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Submission == null)
            {
                return NotFound();
            }

            var submission = await _context.Submission
                .FirstOrDefaultAsync(m => m.SubmissionId == id);
            if (submission == null)
            {
                return NotFound();
            }

            //-----------------------------------------------------------
            var isAuthorized = User.IsInRole(Constants.SubmissionManagersRole) ||
                           User.IsInRole(Constants.SubmissionAdministratorsRole);

            var currentUserId = _userManager.GetUserId(User);

            if (!isAuthorized
                && currentUserId != submission.OwnerID
                && submission.Status != SubmissionStatus.Approved)
            {
                return Forbid();
            }
            //-----------------------------------------------------------

            return View(submission);
        }
        //------------------------------------------------------------------------------

        //// POST: Submissions/Details
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Details(int? id, SubmissionStatus status)
        {
            var submission = await _context.Submission.FirstOrDefaultAsync(m => m.SubmissionId == id);

            if (submission == null)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                var submissionOperation = (status == SubmissionStatus.Approved)
                                                   ? SubmissionOperations.Approve
                                                   : SubmissionOperations.Reject;

                var isAuthorized = await _authorizationService.AuthorizeAsync(User, submission,
                                            submissionOperation);
                if (!isAuthorized.Succeeded)
                {
                    return Forbid();
                }
                submission.Status = status;

                _context.Submission.Update(submission);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(submission);
        }


        //------------------------------------------------------------------------------
        // GET: Submissions/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Submissions/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("SubmissionId,OwnerID,BirdName,BirdInformation,FileName,BirdImage,Status")] Submission submission)
        {
            if (ModelState.IsValid)
            {
                //Save image to wwwroot/image
                string wwwRootPath = _hostEnvironment.WebRootPath;
                string fileName = Path.GetFileNameWithoutExtension(submission.BirdImage.FileName);
                string extension = Path.GetExtension(submission.BirdImage.FileName);
                submission.FileName = fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                string path = Path.Combine(wwwRootPath + "/Photos/", fileName);
                using (var fileStream = new FileStream(path, FileMode.Create))
                {
                    await submission.BirdImage.CopyToAsync(fileStream);
                }

                //--------------------------------------------------------
                submission.OwnerID = _userManager.GetUserId(User);

                var isAuthorized = await _authorizationService.AuthorizeAsync(
                                                            User, submission,
                                                            SubmissionOperations.Create);
                if (!isAuthorized.Succeeded)
                {
                    return Forbid();
                }
                //------------------------------------------------------------------------
                _context.Add(submission);
                await _context.SaveChangesAsync();
                //return RedirectToAction(nameof(Index));
                return RedirectToAction("Thanks");
            }
            return View(submission);
        }
        //create thanks return view
        public IActionResult Thanks()
        {
            return View();
        }

        // GET: Submissions/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Submission == null)
            {
                return NotFound();
            }

            var submission = await _context.Submission.FindAsync(id);
            if (submission == null)
            {
                return NotFound();
            }
            //----------------------------------------------------------
            // you may need to add two more perameters to get method (bind and submission)
            var isAuthorized = await _authorizationService.AuthorizeAsync(
                                                  User, submission,
                                                  SubmissionOperations.Update);
            if (!isAuthorized.Succeeded)
            {
                return Forbid();
            }

            //-------------------------------------------------------------------
            return View(submission);
        }

        // POST: Submissions/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("SubmissionId,OwnerID,BirdName,BirdInformation,FileName,BirdImage,Status")] Submission submission)
        {
            if (id != submission.SubmissionId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    //Save image to wwwroot/image
                    string wwwRootPath = _hostEnvironment.WebRootPath;
                    string fileName = Path.GetFileNameWithoutExtension(submission.BirdImage.FileName);
                    string extension = Path.GetExtension(submission.BirdImage.FileName);
                    submission.FileName = fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                    string path = Path.Combine(wwwRootPath + "/Photos/", fileName);
                    using (var fileStream = new FileStream(path, FileMode.Create))
                    {
                        await submission.BirdImage.CopyToAsync(fileStream);
                    }

                    //------------------------------------------------------------------

                    var existingSubmission = await _context.Submission.AsNoTracking().FirstOrDefaultAsync(m => m.SubmissionId == id);

                    if (existingSubmission == null)
                    {
                        return NotFound();
                    }

                    var isAuthorized = await _authorizationService.AuthorizeAsync(
                                                 User, existingSubmission,
                                                 SubmissionOperations.Update);
                    if (!isAuthorized.Succeeded)
                    {

BirdRecogniser02/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BirdRecogniser02</title>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BirdRecogniser02.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.5.12/cropper.min.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.5.12/cropper.min.js"></script>

</head>
<body class="m-0">
    <header>
        <nav class="navbar navbar-expand-xl navbar-toggleable-xl bg-white border-bottom box-shadow">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/image/logo2.png" alt="Logo" width="100%">
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-xl-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="RecogniseDemo" asp-action="Index">Recognise</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Submissions" asp-action="Create">Contribute</a>   

                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Mobile">Get the App</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="About">About Us</a>
                        </li>
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>*@
                    </ul>
                    <partial name="_LoginPartial"   />
                </div>
            </div>
        </nav>
    </header>


    <div class="container-fluid pagecontent">
        <main role="main" class="">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container-fluid text-center">
            Made with ♡ in Wellington© 2023 Bird Recogniser
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>